# Generated by Django 3.2 on 2022-06-15 16:51

import datetime
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0015_auto_20220318_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2022, 6, 15))]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_datetime',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 6, 15, 16, 51, 57, 153728, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='start_datetime',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 6, 15, 16, 51, 57, 153696, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
